name: sudoku
description: A Sudoku game made with Flutter, and integrated with Gemini.
homepage: https://github.com/thecodexhub/sudoku
version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.22.1

dependencies:
  bloc: ^8.1.3
  cloud_firestore: ^5.6.2
  dio: ^5.7.0
  envied: ^1.1.0
  equatable: ^2.0.7
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  loading_indicator: ^3.1.1
  rxdart: ^0.28.0
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.11
  envied_generator: ^1.0.0
  fake_async: ^1.3.1
  fake_cloud_firestore: ^3.1.0
  firebase_core_platform_interface: ^5.4.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockingjay: ^0.5.0
  mocktail: ^1.0.3
  plugin_platform_interface: ^2.1.8
  url_launcher_platform_interface: ^2.3.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/licenses/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
