// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_development.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8QwjgMLGGoqrC18EqYNNelHAFqun--xo',
    appId: '1:625889474527:web:7d83cf9da61a04194f766a',
    messagingSenderId: '625889474527',
    projectId: 'sudoku-gemini-dev',
    authDomain: 'sudoku-gemini-dev.firebaseapp.com',
    storageBucket: 'sudoku-gemini-dev.appspot.com',
    measurementId: 'G-SYEEE9PEK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaxrZceIou6lhQUWfryVkOlxAocWwPW4c',
    appId: '1:625889474527:android:37572e6f3ee666b34f766a',
    messagingSenderId: '625889474527',
    projectId: 'sudoku-gemini-dev',
    storageBucket: 'sudoku-gemini-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDePWlqScHvs5zyTlABennhNqI5Mf_pvI',
    appId: '1:625889474527:ios:46175ffdaa2a35dc4f766a',
    messagingSenderId: '625889474527',
    projectId: 'sudoku-gemini-dev',
    storageBucket: 'sudoku-gemini-dev.appspot.com',
    iosBundleId: 'dev.thecodexhub.sudoku.dev',
  );
}
