// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoHpi_z6v2Wbltn-SOHTypZ45nRsssRdY',
    appId: '1:316874251532:web:7c742219a94130ea6efd29',
    messagingSenderId: '316874251532',
    projectId: 'sudoku-gemini-stg',
    authDomain: 'sudoku-gemini-stg.firebaseapp.com',
    storageBucket: 'sudoku-gemini-stg.appspot.com',
    measurementId: 'G-M1SC3KCQD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0d1vG626m4Kp37IDBqjz8HxtIStU-BzQ',
    appId: '1:316874251532:android:fd0708e8a0c0a4276efd29',
    messagingSenderId: '316874251532',
    projectId: 'sudoku-gemini-stg',
    storageBucket: 'sudoku-gemini-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvy60lxcy1AirxhI04Lbr8LXH6Wmuyjj0',
    appId: '1:316874251532:ios:c4c2f2bf54a201d26efd29',
    messagingSenderId: '316874251532',
    projectId: 'sudoku-gemini-stg',
    storageBucket: 'sudoku-gemini-stg.appspot.com',
    iosBundleId: 'dev.thecodexhub.sudoku.stg',
  );
}
