// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1YuSZUyp7ltXaztIIT6OaMr_JJmZm9TA',
    appId: '1:1047240251784:web:f80d96536b03020183c23d',
    messagingSenderId: '1047240251784',
    projectId: 'sudoku-gemini',
    authDomain: 'sudoku-gemini.firebaseapp.com',
    storageBucket: 'sudoku-gemini.appspot.com',
    measurementId: 'G-ZCZXFSFVYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZa-L5uhYmCMUVrShOKf0ADfiCSomIoLk',
    appId: '1:1047240251784:android:1ed17c169825484883c23d',
    messagingSenderId: '1047240251784',
    projectId: 'sudoku-gemini',
    storageBucket: 'sudoku-gemini.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7yC-6iKsMLjlsRHG6HI0_qNCUCkMVhLs',
    appId: '1:1047240251784:ios:9ec726836eedb77b83c23d',
    messagingSenderId: '1047240251784',
    projectId: 'sudoku-gemini',
    storageBucket: 'sudoku-gemini.appspot.com',
    iosBundleId: 'dev.thecodexhub.sudoku',
  );
}
